### ISSUE TITLE
Create a Template for the "User-Defined Exceptions" that can alterated in-game according to the need

### ISSUE THREAD

**Issue by DeKuHigh** [DeKuHigh/UnityLibrary#11]
This template can be tested on any one of the open-world examples for testing its compatibility.

**Comment by agriyakhetarpal** [comment]
Hi @DeKuHigh, could you please assign this to me? If I understand this correctly, I can use any real-world parameters for this one: such as temperature or similar?

**Comment by DeKuHigh** [comment]
Yeah Sure @agriyakhetarpal , Just make sure to create the testing environment in Unity interface.

**Comment by agriyakhetarpal** [comment]
Linked the PR above, I've implemented a user-defined exception that tests if temperature is set to zero and raises it appropriately

**Comment by DeKuHigh** [comment]
> Linked the PR above, I've implemented a user-defined exception that tests if temperature is set to zero and raises it appropriately

Yeah sure I will look into your PR
